import {
  Star,
  StarOff,
  Copy,
  Pencil,
  Edit,
  Trash,
  MoreVertical,
  Plus,
  Check,
  X,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  Menu,
  Search,
  FileText,
  Settings,
  Palette,
  SunMedium,
  Moon,
  PanelLeft,
  FolderPlus,
  Folder,
  Layout,
  Gift,
  Upload,
  Download,
  Save,
  FileJson,
  AlertCircle,
  AlertTriangle,
  FileUp,
  FileDown,
  File,
  Pin,
  PinOff,
  Info,
  RefreshCw,
  Github,
  Loader
} from "lucide-react";

export const Icons = {
  star: Star,
  starOff: StarOff,
  starFilled: Star,
  copy: Copy,
  pencil: Pencil,
  edit: Edit,
  trash: Trash,
  moreVertical: MoreVertical,
  plus: Plus,
  check: Check,
  x: X,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  menu: Menu,
  search: Search,
  fileText: FileText,
  settings: Settings,
  palette: Palette,
  sun: SunMedium,
  moon: Moon,
  panelLeft: PanelLeft,
  folderPlus: FolderPlus,
  folder: Folder,
  layout: Layout,
  gift: Gift,
  upload: Upload,
  download: Download,
  save: Save,
  fileJson: FileJson,
  fileExport: FileDown,
  fileUp: FileUp,
  file: File,
  alertCircle: AlertCircle,
  alertTriangle: AlertTriangle,
  pin: Pin,
  pinOff: PinOff,
  info: Info,
  refresh: RefreshCw,
  github: Github,
  loader: Loader,
  bot: AlertCircle
}; 